import * as method from "./method";
import { addPrototype } from "../utils";

declare global {
  interface Object {
    $mapValues(fn: (value: any, key: string | number, object: object) => any): object;
  }
}

/**
 * Creates an object with the same keys as the provided object and values
 * generated by running the provided function for each value
 * @memberof Object.prototype
 * @param {Function} fn
 * @returns {Object}
 * @example
 * const users = {
 *   fred: { user: "fred", age: 40 },
 *   pebbles: { user: "pebbles", age: 1 }
 * };
 * users.$mapValues(u => u.age); // { fred: 40, pebbles: 1 }
 */
function $mapValues(this: object, fn: (value: any, key: string | number, object: object) => any): object {
  return method(this, fn);
}

addPrototype("$mapValues", $mapValues);
