import mapValues from "./index.js";
import { addPrototype } from "../../utils.js";

declare global {
  interface Object {
    $mapValues(
      fn: (
        value: unknown,
        key: string,
        object: Record<string, unknown>,
      ) => unknown,
    ): Record<string, unknown>;
  }
}

/**
 * Creates an object with the same keys as the provided object and values
 * generated by running the provided function for each value
 * @memberof Object.prototype
 * @function $mapValues
 * @param {Function} fn
 * @returns {Object}
 * @example
 * const users = {
 *   fred: { user: "fred", age: 40 },
 *   pebbles: { user: "pebbles", age: 1 }
 * };
 * users.$mapValues(u => u.age); // { fred: 40, pebbles: 1 }
 */
addPrototype(Object, "$mapValues", mapValues);
