import * as method from "./method";
import { addPrototype } from "../utils";

declare global {
  interface Object {
    $mapKeys(fn: (value: any, key: string | number, object: object) => any): object;
  }
}

/**
 * Creates an object with keys generated by running the provided function for each key
 * and the same values as the provided object
 * @memberof Object.prototype
 * @param {Function} fn
 * @returns {Object}
 * @example
 * { a: 1, b: 2 }.$mapKeys((val, key) => key + val); // { a1: 1, b2: 2 }
 */
function $mapKeys(this: object, fn: (value: any, key: string | number, object: object) => any): object {
  return method(this, fn);
}

addPrototype("$mapKeys", $mapKeys);
