import { addPrototype } from "../../utils";
import * as method from "./method";

declare global {
  interface Object {
    $map(fn: (value: any, key: string, object: object) => { [key: string]: any }): object;
  }
}

/**
 * Creates an object with keys and values
 * generated by running the provided function for each value
 * @memberof Object.prototype
 * @function $map
 * @param {Function} fn
 * @returns {Object}
 * @example
 * const users = {
 *   fred: { user: "fred", age: 40 },
 *   pebbles: { user: "pebbles", age: 1 }
 * };
 * users.$map(u => u.age); // { fred: 40, pebbles: 1 }
 */
addPrototype(Object, "$map", method);
