import "./array/shim";
import "./boolean/shim";
import "./date/shim";
import "./function/shim";
import "./globals/shim";
import "./math/shim";
import "./number/shim";
import "./object/shim";
import "./string/shim";
