import "./array/shim.js";
import "./boolean/shim.js";
import "./date/shim.js";
import "./function/shim.js";
import "./globals/shim.js";
import "./math/shim.js";
import "./number/shim.js";
import "./object/shim.js";
import "./string/shim.js";
