name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    name: Create Release

    concurrency: github-release

    environment:
      name: release
      url: https://github.com/ardalanamini/prototyped.js/releases

    runs-on: ubuntu-latest

    needs:
      - test

    steps:
      - uses: actions/checkout@v2

      - name: Changelog
        id: changelog
        uses: ardalanamini/auto-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ${{ steps.changelog.outputs.changelog }}

  publish-npm:
    name: Publish to NPM

    concurrency: npm-release

    environment:
      name: release
      url: https://www.npmjs.com/package/prototyped.js

    runs-on: ubuntu-latest

    needs:
      - release

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - run: npm ci

      - run: npm run build:hybrid

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-gpr:
    name: Publish to GitHub Packages

    concurrency: gpr-release

    environment:
      name: release
      url: https://github.com/ardalanamini/prototyped.js/packages

    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    needs:
      - release

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@ardalanamini'

      - run: sed -i 's/"name":\ "prototyped.js"/"name":\ "@ardalanamini\/prototyped.js"/g' package.json package-lock.json

      - run: npm ci

      - run: npm run build:hybrid

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
